### PR TITLE
fix/favicons stream never ends

### PR DESCRIPTION
**Pull request by jraoult**
This PR makes sure we trigger the `end` event on the favicons resources stream.

I added a listener for `close` event of the the underlying `ServerResponse` stream (which doesn't trigger the `end` event by design). I left the `end` event in case `generateFaviconStream` is refactored and the returned streams starts triggering the `end` event instead of the `close` event.

### CODE REVIEW

**Comment by haydenbleasel** [comment]
Awesome. Just to clarify, what's the deal with `close` vs `finish`?

**Comment by jraoult** [comment]
@haydenbleasel that is a very good question because indeed it should be `finish`. But when I tried finish I got and error:
```
Error: stream.push() after EOF
    at readableAddChunk (/Users/jraoult/development/projects/mixtube/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:168:15)
    at DestroyableTransform.Readable.push (/Users/jraoult/development/projects/mixtube/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/jraoult/development/projects/mixtube/node_modules/gulp-favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at Parse.<anonymous> (/Users/jraoult/development/projects/mixtube/node_modules/gulp-favicons/index.js:64:30)
    at Parse.emit (events.js:107:17)
    at /Users/jraoult/development/projects/mixtube/node_modules/gulp-favicons/node_modules/favicons/node_modules/unzip/lib/parse.js:109:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

It looks like `finish` is triggered before the last `entry` event is triggered. I think it is because the `ServerResponse` triggers finish but the unzip parser continues to asynchronously parse the content an continues to deliver entries.

TBH I think the right think to do would be to refactor `generateFaviconStream` to return a new stream that triggers the `end` event so that we don't have to know the implementation details when using the API.

**Comment by haydenbleasel** [comment]
Agreed on the refactor, tbh I probably wouldn't know how to implement it as well as you can. Reckon you can do another PR? Thanks for your time so far btw :)

**Comment by jraoult** [comment]
@haydenbleasel no worries. I'll try to take a look at that asap.

**Comment by jraoult** [comment]
Another catch: https://github.com/EvanOxfeld/node-unzip/issues/2. Basically, the unzip module should trigger the `end` event but it doesn't and it is a bug. People seems to move to https://github.com/cthackers/adm-zip which triggers the `end` event. May be a little overkill for us though.

**Comment by haydenbleasel** [comment]
Yeah the `adm-zip` module looks better, I'm all for using that :)

**Comment by jessaustin** [comment]
@jraoult I think your issue link has a typo it seems it should be EvanOxfeld/node-unzip#21. I was confused for a moment! :confused: Also I'm not sure how we could use `adm-zip` as it seems to just deal with files and not streams?

When I monkeypatch `node-unzip` to log all emits I get this:

    pipe
    entry
    [...37 entries...]
    entry
    finish
    unpipe
    entry
    entry
    entry
    entry
    entry
    close

How would everyone feel about `favicons.generateFaviconStream()` watching for *either* `close` or or `end`, then emitting `end` in turn? Based on my limited testing, I don't think we can use `unpipe` or `finish`.

**Comment by jraoult** [comment]
@jessaustin yep I think it is the right thing to do. Just make sure end is only emitted once.

**Comment by jessaustin** [comment]
When `end` is emitted, is it the last event emitted, or is it followed (or, I don't know, immediately preceded) by `close`?

**Comment by jraoult** [comment]
You always get close after end as far as I can remember but I couldn't find a way to  consistently reproduce this case.

**Comment by haydenbleasel** [comment]
@jraoult @jessaustin This one's good to go as well?

**Comment by jraoult** [comment]
I just need to update the dependency once you published the new favicons to npm
On 19 Apr 2015 8:38 pm, Hayden Bleasel <notifications@github.com> wrote:@jraoult @jessaustin This one's good to go as well?

**Comment by haydenbleasel** [comment]
Okay, no worries, I'll update it now (check NPM in 5 mins). I haven't had a chance to test any of these new things so I hope they're working lmao.



—

**Comment by haydenbleasel** [comment]
@jraoult Done. Go ahead mate :+1:

**Comment by jraoult** [comment]
@haydenbleasel I was checking that more closely, I actually think it is all good since @jessaustin made sure `favicons` emits `end` event: no need to merge this since no change is required in `gulp-favicons`.

**Comment by haydenbleasel** [comment]
@jraoult Okay no worries champ. Close this issue?

**Comment by jraoult** [comment]
@haydenbleasel just testing right now. I'll close if everything is ok.

**Comment by haydenbleasel** [comment]
Sounds good :+1:

**Comment by jraoult** [comment]
https://github.com/haydenbleasel/favicons/pull/38 fixed this one so this PR is not necessary anymore. Thanks @jessaustin

**Pull request closed without merging**
