### PR TITLE
Add replaceHTML to options

### PR DESCRIPTION
**Pull request by mikew**
When enabled the plugin will use `$.html` instead of `$.append`.

### CODE REVIEW

**Comment by haydenbleasel** [comment]
Hey @mikew, I think we can work on this and come up with a more elegant solution. What's the use case for this?

**Comment by mikew** [comment]
I'm using `gulp-favicons` to build a partial that will be included in jade or something similar, and without this the included file would grow each time the favicon was changed.

What do you think about allowing a custom method to modify the HTML? Then the user could:

```javascript
let options = {
  modifyHTML (target, code, $) {
    // `target` is $('head') || $.root()
    // `code` is the markup
    // `$` is cheerio
  }
}

favicons(options)
```

But then again, all this is because our build system processes assets before views.

**Comment by haydenbleasel** [comment]
Perhaps a better method is to inheritly remove existing HTML tags with attribute selectors e.g. `link[rel="favicons"]`? Therefore we remove the need for a new option and also prevent doubling up on selectors.

**Comment by mikew** [comment]
Now it loops through all `meta` and `link` elements in `code` and looks for any existing elements in `target`, updating or appending as it goes.

I did also add the option for the user to specify a function for `modifyHTML`, but if you don't want it I'll remove it.

**Comment by haydenbleasel** [comment]
Hey @mikew, I wrote a custom solution for this in `gulp-favicons@2.1.2`.

**Comment by mikew** [comment]
Right, I'll continue using my fork since your version always overwrites "og:image" and will need to play catchup with markup generated from favicons (which isn't that big of a deal since you maintain both packages)

**Comment by haydenbleasel** [comment]
Hey @mike, this is a good point. People are likely to have predefined Favicons tags for each page e.g. og:image.

**Comment by haydenbleasel** [comment]
Hey @mikew, lemme come up with some simpler methods for this and I'll get back to you. But we will get this feature in.

**Comment by haydenbleasel** [comment]
Guh I keep hitting the wrong button

**Comment by haydenbleasel** [comment]
Hey @mikew, the Favicons streaming API has become part of the master module so we're moving the issue there.

**Pull request closed without merging**
